name: Update Google Scholar Citations and Purge Cache

on:
  schedule:
    # Runs at 8:00 AM UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches:
      - main # Or your default branch
    paths:
      - '.github/workflows/google_scholar_crawler.yaml'
      - 'google_scholar_crawler/**'

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write

    steps:
    - name: Checkout main branch code
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r google_scholar_crawler/requirements.txt

    - name: Run Scraper
      id: scrape
      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        PYTHONUNBUFFERED: "1"
      run: |
        python google_scholar_crawler/main.py

    - name: Deploy data to orphan branch
      run: |
        # First, create a list of the files we are about to deploy
        find . -maxdepth 1 -type f -name "*.json" > files-to-purge.txt
        echo "List of files to purge has been saved."

        # Configure Git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Deploy using an orphan branch
        git checkout --orphan google-scholar-stats
        git rm -rf . || exit 0
        git add -f ./*.json
        git commit -m "Deploy latest citation data at $(date -u)"
        
        echo "Pushing data-only branch to repository..."
        git push origin google-scholar-stats --force

    # THIS STEP NOW RUNS AFTER THE DEPLOYMENT
    - name: Purge jsDelivr Cache
      run: |
        echo "Starting jsDelivr cache purge using the saved list..."
        # Read the list of files that were just deployed
        if [ ! -f files-to-purge.txt ]; then
            echo "files-to-purge.txt not found. Skipping purge."
            exit 0
        fi

        # Loop through the filenames in the text file
        while IFS= read -r file; do
          # Remove the leading './' from the filename
          filename=$(basename "$file")
          # Construct the purge URL for the file in the google-scholar-stats branch
          purge_url="https://purge.jsdelivr.net/gh/${{ github.repository }}@google-scholar-stats/${filename}"
          echo "Purging: $purge_url"

          status_code=$(curl -s -o /dev/null -w "%{http_code}" "$purge_url")
          echo "Status code for $filename: $status_code"
          sleep 1
        done < files-to-purge.txt

        echo "Cache purge completed."